sudo: required

language: cpp

matrix:
  include:
    - os: linux
      services: docker
      before_install: docker pull glportal/whale-gcc:bullet285
      script:
        - set -e
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc:bullet285 bash -c "cmake -G Ninja ./; ninja -j 4; ninja tests;"
    - os: osx
      osx_image: xcode8.3
      compiler: gcc
      git:
        submodules: false
      before_install:
        - brew update
      install:
        - brew install gpg2
        - brew uninstall gpg
        - command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
        - gpg2 --keyserver hkp://2a01:4f8:222:2401:1::179 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
        - gpg2 --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        - rvm get head
        - brew install gcc
        - brew install assimp
        - brew install libepoxy
        - brew install sdl2
        - brew install sdl2_mixer
        - brew install bullet
        - brew install tinyxml2
        - brew install unittest-cpp
        - brew install freeimage
      before_script:
        - git submodule update --init --recursive
        - mkdir build && cd build
        - export CC=gcc CXX=g++
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..
        - make -j4
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      git:
        submodules: false
      before_install:
        - brew update
      install:
        - brew install gpg2
        - brew uninstall gpg
        - command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
        - gpg2 --keyserver hkp://2a01:4f8:222:2401:1::179 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
        - gpg2 --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        - rvm get head
        - brew install assimp
        - brew install libepoxy
        - brew install sdl2
        - brew install sdl2_mixer
        - brew install bullet
        - brew install tinyxml2
        - brew install unittest-cpp
        - brew install freeimage
      before_script:
        - git submodule update --init --recursive
        - mkdir build && cd build
      script:
        - set -e
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..
        - make -j4

notifications:
  irc: "chat.freenode.net#glportal"
  slack: glportal:6owD9V6VXhGmM7yyEd2hIZue
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ea210c016747790b4fa4
    on_success: always
    on_failure: always
    on_start: never
